### ISSUE TITLE
ブランチ構成の変更

### ISSUE THREAD

**Issue by Juris710** [appnavi/appnavi.github.io#43]
### 現在のブランチ構成

現在のブランチ構成は次のようになっている。

- `master`：サイトのhtmlを管理
- `nobu_kosugimaru`：サイトのsource codeを管理
- (その他)

このブランチ構成には次のような問題がある。

- PRがMergeされると自動でIssueをCloseする機能が使えない。[(出典)](https://docs.github.com/ja/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)
  - 例えばPRに`Close: #1`とかくと、`Merge Pull Request`ボタンを押すことでIssue `#1`がCloseされる。
- `nobu_kosugimaru`はタイポしやすい。

### 新たなブランチ構成の提案

次のようなブランチ構成を提案する。

- `main`：デフォルトブランチ。サイトのsource codeを管理（現`nobu_kosugimaru`）
- `gh-pages`：サイトのhtmlを管理（現`master`）
- (その他)

ただし、`main`ブランチを新しく作るのではなく、`nobu_kosugimaru`を`main`にリネームする。
`master`にリネームしない理由は次の2つである。

- Taskが成功するまでは現在の`masterブランチ`を残しておきたい。
- 2020年10月1日からデフォルトブランチの名前が`main`になった[(出典)](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/)ので、それに合わせると都合がいい。

## 作業内容

- [x] `nobu_kosugimaru`ブランチで`package.json`編集
  - `yarn deploy`の内容を`gh-pages -d build`に変更
- [x] `nobu_kosugimaru`ブランチで`yarn deploy`を実行することで、サイトのhtmlを`gh-pages`ブランチへpush。
- [x] GitHub Pagesの設定の`sources`を`master`から`gh-pages`に変更。
- [x] GitHub上で`nobu_kosugimaru`ブランチを`main`にリネーム。
- [x] デフォルトブランチを`master`から`main`に変更
- [x] 不要になったremoteブランチを削除
  - `origin/master`

## 備考

このIssueはPRを作成しません。反対意見がなければ、コメントください。
コメントをもらえたら、作業を開始します。

Task終了後に開発する場合、`git clone`し直した方がいいかもしれません。

Task終了後の開発フローは以下のようになります。

- `main`ブランチから派生した`task-*`ブランチでsource codeの改善。
- PRは`main`へのMerge。
- サイトを更新する際は、`main`ブランチで`yarn deploy`を実行。

**Comment by Nobubeck** [comment]
いいと思います！　作業よろしくお願いします！

**Comment by Juris710** [comment]
Taskが終了しました。
